services:
  database:
    image: mysql:8.4
    container_name: trello-db

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./services/database:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: ./services/backend

    container_name: trello-backend

    ports:
      - "8080:80"

    environment:
      DB_HOST: database
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}

    depends_on:
      - database

volumes:
  mysql_data: